// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zaceyszncohhtbkipchl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InphY2V5c3puY29oaHRia2lwY2hsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA3MDI4NDAsImV4cCI6MjA2NjI3ODg0MH0.HVdvTWB_ZIVisTjSv-wEVd311h1W5yTbqVFmxdHv2tk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);